# Generated by Django 4.1.5 on 2023-01-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('blog', '0003_alter_blogpagegalleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='image1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
